- exec/BuildDocs.hs
- src/Thentos/Backend/Api/Proxy.hs
- src/Thentos/Backend/Api/Simple.hs
- src/Thentos/Backend/Core.hs
- tests/Thentos/Backend/Api/SimpleSpec.hs
(See comment in the test case on why this is a 500 error and not something more sane.)
> Fail on requests with unknown headers matching X-Thentos-*.

- src/Thentos/Backend/Api/Adhocracy3.hs
- src/Thentos/DB/Trans.hs
- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Pages.hs
- src/Thentos/Smtp.hs
When someone tries to sign up with an email address that we already have in the database, we now send a "By the way, you're already signed up for Thentos" email instead of creating an unconfirmed user with the same email address. However, the user still gets the same response from the frontend, to avoid leaking user data.
> Handle attempts to create new user with existing email address

- src/Thentos/Config.hs
- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Pages.hs
- src/Thentos/Types.hs
- tests/Thentos/Backend/Api/SimpleSpec.hs
- tests/ThentosSpec.hs
also fixes bug introduced unnoticed a bit earlier.
> Split up roles into two types (maintains representation in config files)

- src/Thentos/Frontend/Handlers.hs
loginService would create a new session whenever a user logged into a service.
That isn't the desired behaviour. Instead, the service login should be added
to an existing thentos session.
> Fix behaviour of loginService

- tests/MetaSpec.hs
- tests/Thentos/FrontendSpec.hs
Fixes #104 and fixes the original problem in the tests.
> Clarify use of `before` and `after` in hspec

- src/Thentos/Frontend.hs
Fixes #98 
As far as I can tell, snap only writes to stderr during snaplet initialisation. Log messages already go to `log/access.log` and `log/error.log`.
> Stop snaplet initialisers writing to stderr

- src/Thentos/Backend/Api/Adhocracy3.hs
- src/Thentos/Backend/Api/Simple.hs
- src/Thentos/Backend/Core.hs
This solution also works for 4xx/5xx responses.
Fixes the Servant part of #112.
> Add Cache-Control headers to all GET/HEAD responses from Servant.

- docs/styleguide.md
Rationale:
* I consider anything between 100 and 120 a reaonable line length limit, so
that's negotiable. But I think 140 is too long, and since I notice that
Matthias' comment lines have at most 100 chars I went for the lower limit
;)
* I'm used to \x for lambdas and it seems more popular than \ x.
Random examples from the web:
https://wiki.haskell.org/Anonymous_function
http://learnyouahaskell.com/higher-order-functions#lambdas
If the changes are adapted, I volunteer to adapt the existing code base,
if desired.
> Proposed changes to layout section of styleguide.

- src/Thentos/Action.hs
- src/Thentos/Backend/Api/Adhocracy3.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Transaction/Transactions.hs
- tests/Thentos/ActionSpec.hs
Module `Thentos.Action` has not labels attached to all actions.
Do not merge yet!  Missing:
1. test suite needs to be adjusted to the more restrictive access.
2. address FIXMEs in `updateUserField`, `confirmUserEmailChange`, ` startServiceSession`, `endServiceSession`.
> Labels for Action

- src/Thentos/Backend/Api/Adhocracy3.hs
- src/Thentos/Backend/Api/Adhocracy3Sso.hs
- src/Thentos/Backend/Api/Auth.hs
- src/Thentos/Backend/Api/Proxy.hs
- src/Thentos/Backend/Core.hs
Allows redefining the names used for custom headers.
This is used in the A3 proxy to read and write the headers which A3 understands, e.g. "X-User-Path" instead of "X-Thentos-User".
> Configurable custom header names

- src/Thentos/Action.hs
- src/Thentos/Action/Core.hs
- src/Thentos/Backend/Api/Adhocracy3.hs
- src/Thentos/Backend/Core.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Handlers/Combinators.hs
- src/Thentos/Transaction/Core.hs
- src/Thentos/Transaction/TH.hs
- src/Thentos/Transaction/Transactions.hs
- src/Thentos/Types.hs
- tests/Thentos/Transaction/CoreSpec.hs
- turn ThentosError into a data family that can be extended by
library users.
- this allows trans_..-functions to throw errors in any AsDB type.
> Polymorphic error types for transactions.

- devel.config-a3-sample
- src/Thentos/Action.hs
- src/Thentos/Backend/Api/Adhocracy3.hs
- src/Thentos/Backend/Api/Proxy.hs
- src/Thentos/Config.hs
- tests/Test/Config.hs
- tests/Thentos/Backend/Api/Adhocracy3Spec.hs
* Add support for forwarding requests from users that aren't logged in.
* If no X-Thentos-Service is specified, we use a default proxied app, if  configured (new section in the config).
* Add sample config for running A3 with Thentos in proxy mode.
Part of the ongoing work on #110.
> Proxy module: allow anonymous requests and a default proxy

- src/Thentos/Action.hs
- tests/Thentos/ActionSpec.hs
Many of the tests in ActionSpec were not actually testing actions that all, but using the underlying transactions directly. This adapts the tests to actually use the actions instead.
> Fix tests in ActionSpec

- thentos-adhocracy/devel.config
- thentos-core/src/Thentos/Config.hs
Fixes #176.
There is now also a nice error message if the specified command is unknown.
I haven't specifically handled the "crash reliably if there are two constructors that are only distinguishable if case sensitively parsed" requirement, but I think if someone defines an enum
data Command = Run | RuN | ...
that's pathological enough to not deserve special treatment.
The current implementation will simply select the first matching constructor in that case.
> Caseless command-name parsing

- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Action/Core.hs
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/src/Thentos/Test/Core.hs
- Relax constraints of the `Extends` class by not forcing a `EmptyDB` instance.
- Provide a type synonym for actions that makes signatures a lot more readable.
- Use throughout (even where it is more restrictive than necessary).
> Type synonym for superset of common class constraints.

- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-tests/bench/Main.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
Fixes #232. Adds a couple of very basic tests related to login and cookies. Plus two typos or so.
> fix csrf test to work with phantomjs

- stack.yaml
- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/thentos-tests.cabal
This allows adding services to the config which will automatically spring into life if the config is read. Fixes #247.
> Autocreate services listed in the config

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Sso.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Transactions.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Types.hs
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Transaction/Transactions.hs
- thentos-core/src/Thentos/Types.hs
This is basically a refactoring for #212 , but since it's nice and self-contained I'd like to merge it before the actual implementation work.
> Move sso-related db fields, transactions and actions into thentos-adhocracy

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Sso.hs
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
- thentos-core/src/Thentos/Types.hs
We didn't sent the X-User-Path  (X-Thentos-User) header in the format understood by the A3 backend.
A3 expects something like
X-User-Path: http://127.0.0.1:6546/principals/users/0000001
but we sent the user name instead.
Fixed by adding a ProxyAdapter that makes the proxy more configurable, and by defining a suitable renderUser function for A3.
> Fix X-User-Path contents for A3

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
See https://github.com/liqd/adhocracy3.mercator/issues/1508
> A3 fails in a confusing way if the user path doesn't end with a slash

- thentos-adhocracy/devel.config
- thentos-core/devel.config
New default is one day for user registration, password reset and email change.
> Change default values to give users more time to click on confirm links

- thentos-adhocracy/devel.config
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
A3 uses "localhost" in the config hence we must too. Otherwise the A3 frontend won't strip the prefix from user names, leading to errors.
Improve logging by showing request method and path+query string.
> Improve config and logging

- thentos-adhocracy/src/Thentos/Adhocracy3/Types.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-core/src/Thentos/Backend/Core.hs
This makes adhocracy-thentos emit errors that like looks those from the A3 backend, so that the frontend will understand them. For all typical error situations that can occur with user creation, account activation, or login, the errors mimic those from the backend exactly.
This means that not only the happy path, but also the usual unhappy paths now work as they should without requiring any further changes at the side of A3.
> A3 style error handling

- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Action/Core.hs
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Frontend.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Frontend/Handlers/Combinators.hs
- thentos-core/src/Thentos/Transaction/Core.hs
- thentos-core/src/Thentos/Transaction/Transactions.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
- thentos-tests/thentos-tests.cabal
This puts some flexibility back into the errors, which got lost when DB extension was removed. Also tries to clean up the conversion to servant errors a bit. Something like this will be needed to get thentos-adhocracy to work with postgres.
I'm not entirely convinced this is the best way to go. Problems:
* `ThentosError ()` now has a bogus error `OtherError ()`
* need `(Show e, Typeable e)` contexts all over the place
* need to add type signatures to specialize actions to `Action () a` from `Action e a`, particularly in tests; compare the the runAction mess in ActionSpec.hs
The alternative approach that I see is to have
```
-- no ThentosError in here
newtype Action e a = Action (ReaderT ActionState (EitherT e (LIO DCLabel)) a)
type ThentosAction = Action ThentosError
```
then define all …
> generalized error type

- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
Fixes #291 by defining a custom error handler for `waiProxyTo`.
> Throw Internal Server Error if the proxied app is unreachable

- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-tests/src/Thentos/Test/Network.hs
This re-adds an activate_account test that got disabled after it required the A3 backend to run. The backend is now faked.
This is a partial fix for #239. However, I left the bigger task of re-testing the user creation process, because the old test relies on the acidstate DB. Since acidstate will soon disappear, it makes more sense to fix that test after our switch to SQL is complete.
> Re-add disabled test for activate_account error handling

- misc/hspec-depend.sh
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-tests/thentos-tests.cabal
It doesn't work (anymore? seems to me like since I upgraded stack).
> reverting the extra source files in cabal attempt to fix test dependency tracking

- thentos-core/thentos-core.cabal
- thentos-tests/thentos-tests.cabal
Current stackage only has cryptonite 0.6, so `stack build` fails with the current bounds.
> Lower cryptonite version bounds to make stack happy

- thentos-tests/src/Thentos/Test/Transaction.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
* The helper functions for running ThentosQuery's from a pool have been
renamed for clarity
* rowCountShouldBe (introduced yesterday) now reports as error location the
place where it was called rather than its own implementation
> Two refactorings to make transaction testing more convenient

- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Frontend/State.hs
- thentos-core/thentos-core.cabal
- thentos-tests/tests/Thentos/Frontend/StateSpec.hs
- thentos-tests/thentos-tests.cabal
This is based on the servant-session package that was already available from a submodule in master.  That package allows to write a middleware that keeps track of a dynamically-typed key-value store accross requests using a cookie.  This patch adds a frontend monad `FAction` that carries a `StateT` value and a function that uses servant-session to keep that value in a cookie.
missing:
- https://hackage.haskell.org/package/clientsession (for secrecy and integrity of the cookie contents)
- frontend-specific errors (can probably fit in `OtherError`)
> Thentos frontend state monad based on servant-session.

- docs/dev-howtos.md
- docs/release_strategy.md
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Docs/Common.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Ends/Types.hs
- thentos-core/src/Thentos/Frontend.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Frontend/Types.hs
- thentos-core/src/Thentos/Sybil/Captcha.hs
- thentos-core/src/Thentos/Types.hs
- thentos-core/thentos-core.cabal
- thentos-tests/bench/Main.hs
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
This resolves Task 41: change registration form validation to check for captcha.
The core API now has "/user/captcha", "/user/register", and "/user/activate" endpoints for creating a user who must be able to solve the captcha correctly. The tests are the best documentation of the workflow.
Suitable frontend (widget) is still missing and handled in a different task. Two other things are missing and will be addressed in different cases:
* If the user name is not unique, the user currently has to solve a new captcha instead of just entering a new name. There is a FIXME in one of the tests for this -- I propose to fix it in Task 42: handle the case that user enters wrong data.
* The "register" endpoint doesn't send out any confirmation emails yet, so the complete workflow doesn't currently …
> Integrate captcha into user registration workflow

- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
This allows the frontend to submit fresh data if user creation fails e.g. because of a duplicate user name, without forcing the user to solve another captcha.
Solves Task 42: handle the case that user enters wrong data.
> Define separate deleteCaptcha (trans)action called only after user creation

- devel.config
- thentos-adhocracy/devel.config
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Config.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
Registration emails are now sent by the addUnconfirmedUser action instead of by its callers. Hence all interfaces (core/REST, core/HTML, a3) will behave in the same way and there is no duplication of functionality.
Resolves Task 60: Modify addUnconfirmedUser action to send emails.
> Modify addUnconfirmedUser action to send emails

- devel.config
- thentos-adhocracy/devel.config
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Config.hs
- thentos-tests/src/Thentos/Test/Config.hs
- more expressive names for yaml lables and types
- one type for all templates (not one for each)
- no built-in default templates in thentos-core
> Tweak Config structure re. email templates

- thentos-tests/tests/Thentos/Backend/Api/PurescriptSpec.hs
This is a minor issue, but it has been asked where the 'honour-it.js' file is coming from, and this patch will make its source go away.  (If you have one in your working copy, please delete by hand once.)
> Purescript delivery test case.

- README.md
On ubuntu 14.04 npm tries to install 6.x version of pulp which has rendered my build broken. Pinpointing the version of pulp to 4.4.1 has fixed that.
Edited:
Pinpointing purescript's version is also added.
> Add version annotation for pulp in README.md

- .gitmodules
- .travis.yml
- misc/thentos-install.sh
- servant-session/CHANGELOG.md
- servant-session/LICENSE
- servant-session/README.md
- servant-session/Setup.hs
- servant-session/servant-session.cabal
- servant-session/src/Servant/Session.hs
- servant-session/test/Servant/SessionSpec.hs
- servant-session/test/Spec.hs
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/src/Thentos/Backend/Api/Auth.hs
- thentos-core/src/Thentos/Backend/Api/Docs/Common.hs
- thentos-core/src/Thentos/Backend/Api/Docs/Proxy.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/thentos-core.cabal
- thentos-tests/thentos-tests.cabal
After this goes to master, after the next update, all previously cloned repos may need to do this:
```
rm -rf .git/modules/submodules/servant-purescript
rm -rf .git/modules/submodules/servant
cabal sandbox delete-source .../submodules/servant/servant-session
./misc/thentos-install.sh
```
> Shrink dependency footprint.

- thentos-core/src/Thentos/Util.hs
Additional comments:
* For ASCII password no further encoding is necessary, having additional test cases with non-ASCII would help going further.
* Make sure to depend on memory>=0.10 (https://github.com/A1kmm/hs-bcrypt/issues/8 https://github.com/vincenthz/hs-memory/commit/17af888d3a34c2322a17b8556f45150c16a98fde)
> Arguments to Crypto.BCrypt.validatePassword where flipped

- thentos-core/src/Thentos/Action.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
Audio captchas where stored in the form "1 2 3 4 5 6", so when users typed "123456", the solution was rejected. Now whitespace is generally ignored and discarded, for both visual and audio captchas. This also means that users can submit visual captcha solutions in the form "abc def" or "abcdef", and both will be accepted.
> Fix audio captchas and generally discard whitespace in captchas

- thentos-core/src/Thentos/Sybil/AudioCaptcha.hs
The previous code would generate '3' for every input byte > 127, so more
than half of the generated digits would be '3'.
> Fix random digit generation for audio captcha

- .travis/script.sh
- thentos-adhocracy/devel.config
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/ProxySpec.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/devel.config
- thentos-core/exec/Captcha.hs
- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Backend/Api/Captcha.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Config.hs
- thentos-core/src/Thentos/Sybil/GraphicCaptcha.hs
- thentos-core/src/Thentos/Transaction/Core.hs
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/tests/Thentos/Action/SimpleAuthSpec.hs
- thentos-tests/tests/Thentos/Action/UnsafeSpec.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/tests/Thentos/Backend/Api/CaptchaSpec.hs
- thentos-tests/tests/Thentos/Backend/Api/PureScriptSpec.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
- thentos-tests/tests/Thentos/Frontend/Handlers/CombinatorsSpec.hs
- thentos-tests/tests/Thentos/Frontend/StateSpec.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
- thentos-tests/tests/Thentos/Sybil/CaptchaSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
- thentos-tests/tests/Thentos/TypesSpec.hs
- thentos-tests/thentos-tests.cabal
The original purpose of this branch is to get rid of absolute path names in compiled executables, which I suspect are served by cabal's `getDataFileName` in the generated module `Path_package_name`.
The config type now allows for a field `root_path` that is `.` by default.  Since this is configifier, you can also use the cli or set `ROOT_PATH` in the shell environment if `.` is not adequate.
I also cleaned up the test suite to work with the new content type and create databases and action states in a more coherent way.
> Path handling (across different dev and op scenarios)

- thentos-adhocracy/src/Thentos/Adhocracy3/Action/Types.hs
- thentos-core/schema/schema.sql
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Types.hs
- thentos-core/src/Thentos/Util.hs
- thentos-core/thentos-core.cabal
- thentos-tests/bench/Main.hs
- thentos-tests/src/Thentos/Test/Arbitrary.hs
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
- thentos-tests/tests/Thentos/UtilSpec.hs
- thentos-tests/thentos-tests.cabal
Support importing users with `bcrypt`-protected passwords.
- Store `HashedSecret` as `bytea` in DB.
- Change names of `verify*` functions.
- Refactor `hashSecret`, `hashSecretWith`: separate pure code from effects.
- Re-think test case in `ActionSpec`.
- Tests.
> Support import of bcrypt data.

- thentos-adhocracy/devel.config
- thentos-adhocracy/src/Thentos/Adhocracy3/Action.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Action/Types.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Action/Unsafe.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-core/src/Thentos/Transaction/Core.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/bench/Main.hs
- thentos-tests/src/Thentos/Test/Arbitrary.hs
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/tests/Thentos/Action/SimpleAuthSpec.hs
- thentos-tests/tests/Thentos/Action/UnsafeSpec.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
- thentos-tests/tests/Thentos/TypesSpec.hs
- thentos-tests/thentos-tests.cabal
This largely fulfills Taiga Task 75: Integrate password reset endpoints into thentos-adhocracy API.
UPDATE: this PR should now be complete and has been successfully tested to work with A3 in proxy mode.
Fixes #321 (the A3 backend is no longer needed; the A3 frontend is still used, but that's intentional). Also fixes #407.
~~Also, I disabled a test that checks whether short passwords are rejected -- in A3 they are, in Thentos not yet. It makes almost certainly sense to enforce a lower limit, but that also affects all other actions where passwords are set (create user, update password etc.) and it thus unrelated to this PR.  (see #463)~~
> Integrate new password reset into thentos-a3 api

- stack.yaml
- thentos-core/thentos-core.cabal
These are not used directly but were added to please Cabal at some point:
asn1-encoding ==0.9.2
asn1-parse ==0.9.1
asn1-types ==0.3.0
x509 ==1.6.1
x509-validation ==1.6.2
The Data.EitherR.fmapL is used from the errors package. This relax its
constraints to (>=2.0.0 && <2.1).
> Add a stack.yml file

- thentos-core/src/Thentos/Action/Core.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Frontend/State.hs
- thentos-core/src/Thentos/Types.hs
- thentos-core/src/Thentos/Util.hs
- thentos-core/thentos-core.cabal
* Removes the dependency on `errors`
* `fmapL` can be replaced by `over _Left` or `first`
* `fmapLM` can be replaced by `_Left` or `traverseOf _Left`
* `fmapLTM` was no longer used
> [Issue #465] Refactoring: _Left subsumes fmapL* functions

- thentos-core/src/Network/HostAddr.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/thentos-core.cabal
- thentos-tests/tests/Network/HostAddrSpec.hs
- thentos-tests/tests/Thentos/Action/SimpleAuthSpec.hs
* Instead of `inet_addr`, use `getAddrInfo` which supports IPv6
* A new module `Network.HostAddr` including:
* `HostAddr` a type wrapping the different kind of addresses
* `getHostAddr` a wrapper over `getAddrInfo` returning a `HostAddr`
* `hostAddr` extract `HostAddr` from a `SockAddr`
> [Issue #455] Add support for IPv6 addresses in allow_ips configuration

- Makefile
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/src/Thentos/Config.hs
- thentos-core/thentos-core.cabal
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/thentos-tests.cabal
New feature: shell variables work with prefix `THENTOS_`.
> Upgrade configifier

- thentos-tests/src/Thentos/Test/Config.hs
Indeed the command `cat` might be elsewhere as in `NixOS` for instance.
> Use `cat` instead of `/bin/cat` for sendmail_path

- thentos-core/src/Thentos/Backend/Core.hs
Fixes #474. There is still a FIXME in the new code (not sure whether that matters in practice), but at least it covers the intended use case of converting aeson errors to JSON.
> Return all rest errors with content-type json

- thentos-core/src/Control/Monad/Except/Missing.hs
- thentos-core/src/Servant/Missing.hs
- thentos-core/src/Thentos/Action/Types.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Frontend/Handlers/Combinators.hs
- thentos-core/src/Thentos/Frontend/Pages.hs
- thentos-core/src/Thentos/Frontend/State.hs
- thentos-core/thentos-core.cabal
* Move `finally` into the new module `Control.Monad.Except.Missing`
* Move `formH` into the new module `Servant.Missing`
* Add a `MonadAction` context synonym to be used instead of some
occurrences of `Action`
* Use `for_` instead of `mapM_` when this reads better
* Use `$>` instead of `>>` and `return`
* Use `.=` instead of `modify` and `.~`
* Use `%=` instead of `modify` and `%~`
* Use `use` instead of `gets` and `^.`
* Use `preuse` instead of `gets` and a manual version of `^?`
* Factor the tab switching as `switchTab` and `switchTab'`
> Refactoring

- misc/thentos-install.hs
this is helpful if software depending on thentos-core wants
to depend on servant-lucid and our dev snapshot of servant
at the same time.
> Add submodules/servant/servant-lucid to cabal sandbox.

- thentos-core/src/Servant/Missing.hs
- thentos-core/src/Thentos/Frontend/Handlers/Combinators.hs
We need this in liqd/aula to deliver PlainText versions of
form pages for debugging and development.
> Allow lists of content-types in FormH, not just one.
