- bench/Main.hs
- src/Thentos/DB/Trans.hs
This benchmark has the same problem as the signup one, namely that it spends almost all of its time in scrypt.
> Add login/logout benchmark

- docs/styleguide.md
Please object where necessary!
> Add first (and quite arbitrary) set of rules.

- src/Thentos/Frontend/Pages.hs
> Have redundant password input to avoid mis-typed passwords

- README.md
- misc/selenium/Makefile
- src/Thentos/Frontend/Pages.hs
- tests/Spec.hs
- tests/Test/Config.hs
- tests/Test/Util.hs
- tests/Thentos/Backend/Api/Adhocracy3Spec.hs
- tests/Thentos/Backend/Api/SimpleSpec.hs
- tests/Thentos/FrontendSpec.hs
- tests/ThentosSpec.hs
- thentos.cabal
(not ready for merge yet.  still testing / debugging.)
> Support for webdriver / selenium.

- .travis.yml
- Makefile
- README.md
- tests/Thentos/FrontendSpec.hs
(this is an answer to 
https://github.com/liqd/thentos/commit/bbf2d593db38d17533a2eca9b18c9d0c5138c3c7#commitcomment-10270895)
> Fix travis

- services/helloworld/helloworld.cabal
- services/helloworld/src/Site.hs
- src/Thentos/Api.hs
- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Pages.hs
> Frontend session stuff

- devel.config
- docs/styleguide.md
- src/Thentos.hs
- src/Thentos/Backend/Api/Adhocracy3.hs
- src/Thentos/Backend/Api/Proxy.hs
- src/Thentos/Backend/Api/Simple.hs
- src/Thentos/Backend/Core.hs
- src/Thentos/Config.hs
- src/Thentos/DB/Protect.hs
- src/Thentos/Frontend.hs
- src/Thentos/Smtp.hs
- src/Thentos/Types.hs
- src/Thentos/Util.hs
- tests/Test/Config.hs
- tests/Test/Util.hs
- tests/Thentos/Backend/Api/Adhocracy3Spec.hs
- tests/Thentos/Backend/Api/SimpleSpec.hs
- tests/Thentos/FrontendSpec.hs
- tests/ThentosSpec.hs
- thentos.cabal
There is still room for improvement, but this is my fist shot.
> Move from configurator, optparse-applicative to configifier.

- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Pages.hs
- src/Thentos/Types.hs
Comes with a very simple demonstration.  Missing: body pages for all tabs (to be done separately?).
> Dashboard pagelet

- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Pages.hs
route, entry on index page, pagelet for user details.
> Dashboard (cont.)

- src/Thentos/Api.hs
- src/Thentos/Backend/Api/Proxy.hs
- src/Thentos/DB/Trans.hs
- src/Thentos/Types.hs
- src/Thentos/Util.hs
- tests/Test/Util.hs
The last commit explains that the transactions still work as before.  I would like to update them separately.
> Refactor DB type

- exec/BuildDocs.hs
- src/Thentos/Api.hs
- src/Thentos/Backend/Api/Simple.hs
- src/Thentos/Config.hs
- src/Thentos/DB/Trans.hs
- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Pages.hs
- src/Thentos/Types.hs
- tests/Thentos/Backend/Api/SimpleSpec.hs
- tests/ThentosSpec.hs
Depends on #42 -- please merge #42 first!
> Service Registration

- services/helloworld/helloworld.cabal
- services/helloworld/src/Site.hs
- src/Thentos/Api.hs
- src/Thentos/Types.hs
not sure if these changes are covered by the test suite.  helloworld is currently unbuildable; once it is back, we may want to test it against this.
> Fix: make service login fail if user is not registered with service.

- src/Thentos/DB/Trans.hs
> Document Thentos.DB.Trans.

- cabal.config
- services/helloworld/src/Site.hs
- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Pages.hs
- src/Thentos/Frontend/Types.hs
- tests/Thentos/FrontendSpec.hs
- thentos.cabal
- user registering with service
- snap error handling
- use uri-bytestring package
- various misc refactorings and bug fixes
> Frontend Misc

- src/Thentos/Api.hs
- src/Thentos/DB/Trans.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Pages.hs
This is on top of #50.
Note: I've rebased this branch and squashed wip commits.
> Add service list to logout page

- src/Thentos/Api.hs
- src/Thentos/DB/Protect.hs
- src/Thentos/DB/Trans.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Pages.hs
- src/Thentos/Types.hs
> (Trivial) Fix capitalisation of Timestamp type

- src/Thentos/Api.hs
- src/Thentos/DB/Protect.hs
- src/Thentos/DB/Trans.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Pages.hs
- src/Thentos/Types.hs
> Don't delete userServices when logging user out

- tests/Thentos/FrontendSpec.hs
> Fix wd tests

- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Pages.hs
(trivial.  i did a test run, still works.)
> Cleanup: handler, page, form names.

- src/Thentos.hs
- src/Thentos/Action.hs
- src/Thentos/Action/Core.hs
- src/Thentos/Backend/Api/Simple.hs
- src/Thentos/Backend/Core.hs
- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Handlers/Combinators.hs
- src/Thentos/Transaction/Core.hs
- src/Thentos/Transaction/TH.hs
- src/Thentos/Transaction/Transactions.hs
- src/Thentos/Types.hs
- tests/Test/Util.hs
- tests/ThentosSpec.hs
Fixes #32.
It's not as polymorphic as I would like; I will open an issue on this.  Anyway I think we can merge this as is and take it from here later.
> Polymorphic transactions and actions

- .travis.yml
- .travis/build-cache.sh
- .travis/install.sh
Don't merge this yet, this pr is just there so I can see what travis does.
> Travis dependency cache stuff

- src/Thentos/Action.hs
- src/Thentos/Backend/Api/Simple.hs
- tests/Test/Util.hs
- tests/Thentos/Backend/Api/SimpleSpec.hs
- tests/Thentos/FrontendSpec.hs
- tests/ThentosSpec.hs
Two tests (formerly one) in FrontentSpec still fail, but that should be the last one(s).  Going to fix separately.
> Fix test suite

- src/Thentos/Frontend/Handlers/Combinators.hs
- src/Thentos/Frontend/Pages.hs
> Serve permission denied page on LabelError

- .travis.yml
- README.md
> Remove references to patched servant-pandoc version

- tests/Test/Core.hs
- thentos.cabal
mini-pr, but nice to have it.
next: #97, #98
> tests vs. stdout

- src/Thentos/Frontend/Handlers/Combinators.hs
- src/Thentos/Frontend/Pages.hs
> Frontend "permission denied" handling

- src/Thentos/Action/Core.hs
- src/Thentos/Frontend/Handlers.hs
- src/Thentos/Frontend/Handlers/Combinators.hs
Fixes #105 
Note that this pr is for 2015-05-27-fh-hspec-weirdness, not for master, as discussed.
Also, the tests now pass again (modulo non-deterministic selenium tests). Yay us!
> Allow frontend actions to run with elevated privileges when necessary

- tests/Test/WebDriver/Missing.hs
- tests/Thentos/FrontendSpec.hs
- thentos.cabal
Fixes #111 
Still testing.  DO NOT MERGE.
> `Test.WebDriver.Missing` module for more robust page loads.

- .gitignore
- src/Thentos/Transaction/Transactions.hs
- src/Thentos/Types.hs
> Use separate mappings from user name/email to ID for efficient lookup

- src/Thentos/Frontend.hs
- src/Thentos/Frontend/Handlers.hs
This fixes the Snap part of #112.
> Disable caching of snap responses.

- src/Thentos/Backend/Api/Adhocracy3.hs
- tests/Test/Core.hs
- tests/Thentos/Backend/Api/Adhocracy3Spec.hs
A while ago I wrote a rest api that tries to act like adhocracy3.  I just un-bit-rotted it a little, but there is still one failing test case.
Test case should be fixed before merging.
> Thentos.Backend.Api.Adhocracy3

- src/Thentos/Action.hs
This does *not* fix the issue.  It just mentions it, and it corrects an outdated (or otherwise false) comment.
> Update comment regarding #131.

- src/Thentos.hs
- src/Thentos/Backend/Api/Adhocracy3.hs
- src/Thentos/Backend/Api/Proxy.hs
- src/Thentos/Backend/Core.hs
> Fix proxy module

- src/Thentos/Transaction/Core.hs
- src/Thentos/Transaction/Transactions.hs
- tests/Thentos/Transaction/CoreSpec.hs
Work on #75.
This PR does NOT solve the issue, but:
- it makes writing and composing polymorphic transactions easier,
- it adds test cases that explain how `AsDB` works, and
- it cleans up the code a little.
Can be reviewed and possibly merged.
> Polymorphic Transactions, Actions

- exec/BuildDocs.hs
- thentos.cabal
Fixes #88 and #89 
I've also re-enabled and fixed the Adhocracy3 docs.
> Minor docs improvements

- src/LIO/Missing.hs
- src/Thentos/Action.hs
- src/Thentos/Transaction/Transactions.hs
Fixes most of #158, punting on the fixme in `updateUserField` until I better understand how to fix this.
> Misc label stuff

- docs/styleguide.md
This is meant to document our best practices as we currently use them, not
to change anything substantially.
> Rewrite section on import statements in styleguide

- src/Thentos/Backend/Core.hs
> Fix: servant path combinator for header check does not need value.

- docs/styleguide.md
> Styleguide: test module names.

- HLint.hs
- src/Thentos/Action/Core.hs
- src/Thentos/Backend/Core.hs
- src/Thentos/Transaction.hs
- src/Thentos/Transaction/Core.hs
- src/Thentos/Transaction/TH.hs
- src/Thentos/Transaction/Transactions.hs
- src/Thentos/Types.hs
- tests/Test/Core.hs
- tests/Test/CustomDB.hs
- tests/Test/Types.hs
- tests/Thentos/Transaction/CoreSpec.hs
- tests/Thentos/Transaction/Types.hs
- thentos.cabal
> poly transactions

- src/Thentos/Backend/Api/Adhocracy3.hs
- src/Thentos/Backend/Core.hs
- src/Thentos/Types.hs
This addresses the so-far-unresolved comments from #187.
> User creation fixups

- thentos-core/src/Thentos/Action.hs
Seems to compile just as fine as before.
> Leaner type sig for prepareUserData

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Sso.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Types.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Action/Core.hs
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Transaction/Core.hs
- thentos-core/src/Thentos/Transaction/Transactions.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/src/Thentos/Test/CustomDB.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
Fixes #193; obsoletes #198.
See discussion there.  I hope this time I got it right.  Review should probably happen on the total changes, not individual commits.  (I'd keep the commits anyway in case we ever need to inspect intermediate states.)
> extensible errors (2nd attempt at variant 1)

- thentos-core/src/Thentos/Transaction/TH.hs
> Improve documentation in Thentos.Transaction.TH

- thentos-adhocracy/devel.config
- thentos-core/src/Thentos/Config.hs
- thentos-core/src/Thentos/Types.hs
- thentos-core/thentos-core.cabal
> Simplify proxy setup in config

- thentos-core/src/Thentos/Transaction/TH.hs
This is an appendix to #210, which was closed before I could take a look.
(@fhartwig: #210 looked good, this was the only thing I wanted to change, honestly!  :-)
> Add two lines to Transaction.TH documentation

- thentos-core/src/ThentosDocs.hs
As discussed in https://github.com/liqd/thentos/pull/204/files#r34553959.
> Remove import of unused Thyme instances.

- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Action/Core.hs
- thentos-core/src/Thentos/Smtp.hs
> Handle errors in Thentos.Smtp

- thentos-core/devel.config
- thentos-core/src/System/Log/Missing.hs
- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Config.hs
- thentos-tests/src/Thentos/Test/Config.hs
> Make logger settings configurable

- README.md
- misc/thentos-install.sh
Also turn on -fwith-thentos-executable by default.
> Update README for thentos-install.sh.

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Sso.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/ProxySpec.hs
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
- thentos-core/src/Thentos/Config.hs
- thentos-core/src/Thentos/Types.hs
- thentos-core/thentos-core.cabal
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/src/Thentos/Test/Types.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
- thentos-tests/thentos-tests.cabal
Switch to global client manager (rather than creating a new one per
request).
Add tests for proxied requests.
> Change proxy to use http-reverse-proxy.

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
- thentos-core/src/Thentos/Types.hs
Not there yet, but two little steps in the right direction:
* User tokens weren't serialized correctly.
* Looking up the session based on the X-User-Token header failed because of clearance issues.
> Small steps for making A3 login work

- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Action.hs
> Fix GC auth issue

- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/ProxySpec.hs
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/tests/Thentos/TypesSpec.hs
Also re-adds ability to have non-top-level target URIs for proxies.
> Better validation for ProxyUri.

- .travis.yml
- misc/get-cabal-config.sh
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
Add `-Werror`, and generate a `cabal.config' that accords with the stack versions.
> Werror and other travis details

- .travis.yml
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Frontend.hs
- thentos-core/src/Thentos/Transaction/Core.hs
Fixes #242 (don't merge yet, I want to see travis pass first)
> Use pre-built hlint instead of building it ourselves

- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/ProxySpec.hs
- thentos-tests/src/Thentos/Test/Network.hs
- thentos-tests/thentos-tests.cabal
This makes #266 fail more usefully for me. It also seems to head towards something more correct, but is clearly not the right solution in this state.
> proxy test failure changes (fixes #266)

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Types.hs
- thentos-core/src/Thentos/Backend/Core.hs
Fixes #274:
* Error responses now contain a JSON body with the Content-Type properly set.
* NoSuch... errors are reported as 400 Bad Request instead of 404 Not Found.
> Better error responses

- thentos-adhocracy/src/Thentos/Adhocracy3/Transactions.hs
- thentos-core/src/Thentos/Transaction/Transactions.hs
Should just make things a little more consistent and clearer.
> Use MonadError instead of EitherR helpers for errors.

- thentos-adhocracy/src/Thentos/Adhocracy3.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Sso.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Core.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Transactions.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Types.hs
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Config.hs
Just leaving this here in case someone wants to work on getting thentos-adhocracy up to speed on 2015-08-db. Not sure there's a whole lot done here, but feel free to take over.
> 2015 08 db a3 (WIP, don't merge)

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Docs/Simple.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Sso.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Types.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/ProxySpec.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-core/src/Thentos/Action.hs
- thentos-tests/src/Thentos/Test/Arbitrary.hs
- thentos-tests/src/Thentos/Test/Network.hs
- thentos-tests/thentos-tests.cabal
> Handle password reset in Thentos proxy

- stack.yaml
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/thentos-core.cabal
- thentos-tests/src/Thentos/Test/Network.hs
See https://github.com/haskell-servant/servant/compare/jkarni/400-error-fix?expand=1 for the actual changes.
> Use fixed 400 error servant branch

- thentos-core/src/Thentos/Action.hs
This goes pretty far in removing LIO, this can't really be the right thing to do. Very unsure this should be merged.
It does however make the basic helloworld flow work:
* log in as god/god, create service, copy service id and token to helloworld's devel.config
* navigate to helloworld service, log in via thentos, redirected back
* log out of helloworld service
The last two steps also work as non-god. If we do decide to go ahead with this, I'd write tests for this before merging.
> Remove LIO restrictions to make helloworld service work. Fixes #231.

- .travis.yml
- misc/thentos-install.sh
> 2015 09 jkarni travis cache

- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Frontend/Handlers/Combinators.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-tests/src/Thentos/Test/Network.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
- thentos-tests/thentos-tests.cabal
This branch has two main contributions:
* It prevents not-yet-activated users from logging in.
* It fixes #239 by re-adding a complete user creation + activation test for A3.
> Fix login bug and add tests

- README.md
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Frontend.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Frontend/Pages.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
> Email change

- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Transaction.hs
Authorization control is still work-in-progress and only noted in FIXMEs.
Fixes #318 (the rest of it, transactions were added in #331 already).
> Define actions wrapping transactions for persons and contexts

- Makefile
- thentos-core/src-devel/Paths_thentos_core.hs
- thentos-core/src-devel/cabal_macros.h
afterthought re. #342.  poor testing on my side.  sorry!
> Fix sensei make rules

- thentos-core/schema/schema.sql
- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
> Services are now ownable only by real users, not other services.

- thentos-core/src-devel/Paths_thentos_core.hs
- thentos-core/src-devel/Paths_thentos_core_aux.hs
- thentos-core/thentos-core.cabal
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/tests/ThentosSpec.hs
- thentos-tests/thentos-tests.cabal
> Test infrastructure tweaks

- thentos-core/schema/schema.sql
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Proxy.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
> Group management

- stack.yaml
- thentos-core/src/Servant/Missing.hs
- thentos-core/thentos-core.cabal
- thentos-tests/tests/Servant/MissingSpec.hs
- thentos-tests/thentos-tests.cabal
This is a self-contained step on the way to decommissioning snap.
Missing (can be done elsewhere):
- file upload
- csrf protection
> Servant combinators for digestive-functors

- misc/thentos-install.sh
> Make thentos-install work when invoked without arguments

- docs/terminology.md
> Terminology doc

- docs/sybil.md
This both describes my ideas of captchas and how traffic data and blacklists could be managed.  It also aims at making it explicit what each of the mechanisms is worth.  This should be a useful read for project managers to manage customer expectations and argue in favor of sms-tans.
> Document captchas and blacklists.

- thentos-core/src/Thentos/Config.hs
I think this slipped through in https://github.com/liqd/thentos/pull/357 . @ChristianSi , could you review this?
> Fix default verification mail template

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Frontend/Pages.hs
- thentos-core/src/Thentos/Frontend/State.hs
- thentos-core/src/Thentos/Types.hs
Also created Github issues for them (#399 to #407) and added the bug number.
This resolves story 32: As a Thentos dev I need to have bugs separated from the rest of the FIXMEs, so I can concentrate on solving bugs.
> Scanned all FIXMEs and mark bugs with BUG

- misc/python-dist/.gitignore
- misc/python-dist/setup.py
- misc/python-dist/setup.sh
- misc/python-dist/thentos_adhocracy/__init__.py
- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/src/Thentos/Config.hs
- thentos-core/thentos-core.cabal
- thentos-tests/thentos-tests.cabal
Python egg constructor for thentos-adhocracy.
This is providing the compiled executable and config file as data files to python applications, with a small wrapper script.  no platform sensitivity yet.
> Binary python package

- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
This salvages the good parts of #412.
> A3 api refactorings

- thentos-core/src/Thentos/Types.hs
This is a cherry-pick from #426.
> Drop un-helpful use of ViewPatterns.

- misc/release/thentos-captcha-release.sh
- misc/thentos-install.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/bench/Main.hs
- thentos-tests/thentos-tests.cabal
- cabal bench is working again.
- travis will now report if bench suite has compile time problems.
- new benchmarks for captcha.  results in the haddock comment.
> Benchmark thentos-captcha

- thentos-adhocracy/src/Thentos/Adhocracy3/Action.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Action/Types.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Action/Unsafe.hs
- thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs
- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-core/devel.config
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Api/Docs/Common.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Config.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
A3 integration is still missing, but otherwise this is now ready for review.
> Password reset API

- thentos-adhocracy/tests/Thentos/Adhocracy3/Backend/Api/SimpleSpec.hs
- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-core/src/Thentos/Transaction/Core.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/bench/Main.hs
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/tests/Thentos/Action/SimpleAuthSpec.hs
- thentos-tests/tests/Thentos/Action/UnsafeSpec.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
- thentos-tests/tests/Thentos/TransactionSpec.hs
- thentos-tests/thentos-tests.cabal
See commit comments for details.  Note that the commits have been composed to make code review easier and are not self-contained.
> Refactor addUser, createDefaultUser, test suite

- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Backend/Core.hs
- thentos-core/src/Thentos/Types.hs
- thentos-tests/tests/Thentos/ActionSpec.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
- thentos-tests/tests/Thentos/TypesSpec.hs
> Reject passwords with less than 6 chars

- refresh-i18n/src/Main.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
* Thentos.Transaction: add and use a more flexible variation of returnUnique
* Thentos.Backend.Api.SimpleSpec: use shouldRespondWith more often
> Refactoring in Thentos.Transaction and Thentos.Backend.Api.SimpleSpec

- docs/messaging.md
- stack.yaml
- thentos-core/src/Thentos/Action.hs
- thentos-core/src/Thentos/Action/Unsafe.hs
- thentos-core/src/Thentos/Backend/Api/Docs/Common.hs
- thentos-core/src/Thentos/Backend/Api/Simple.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Smtp.hs
- thentos-core/src/Thentos/Transaction.hs
- thentos-core/src/Thentos/Types.hs
- thentos-core/thentos-core.cabal
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/tests/Thentos/Backend/Api/SimpleSpec.hs
- thentos-tests/thentos-tests.cabal
No support yet for the HTML optional body.
> Basic support to send emails [#472]

- stack.yaml
- thentos-core/devel.config
- thentos-core/src/Servant/Missing.hs
- thentos-core/src/Thentos.hs
- thentos-core/src/Thentos/Config.hs
- thentos-core/src/Thentos/Frontend.hs
- thentos-core/src/Thentos/Frontend/CSRF.hs
- thentos-core/src/Thentos/Frontend/Handlers.hs
- thentos-core/src/Thentos/Frontend/Handlers/Combinators.hs
- thentos-core/src/Thentos/Frontend/Pages.hs
- thentos-core/src/Thentos/Frontend/Pages/Core.hs
- thentos-core/src/Thentos/Frontend/State.hs
- thentos-core/src/Thentos/Frontend/Types.hs
- thentos-core/thentos-core.cabal
- thentos-tests/src/Thentos/Test/Config.hs
- thentos-tests/src/Thentos/Test/Core.hs
- thentos-tests/tests/Thentos/Frontend/Handlers/CombinatorsSpec.hs
- thentos-tests/tests/Thentos/Frontend/StateSpec.hs
- thentos-tests/tests/Thentos/FrontendSpec.hs
- thentos-tests/thentos-tests.cabal
Ready for review:
* docs
* code
TODO:
* tests
> CSRF protection

- thentos-core/src/Servant/Missing.hs
For this to work, we will have to go through the code and replace all occurrances of `Html ()` with `HtmlT m ()`.  Not sure about the implications of that.
> Remove unnecessary restriction to Identity monad in Servant.Missing

- thentos-adhocracy/thentos-adhocracy.cabal
- thentos-core/src/Servant/Missing.hs
- thentos-core/thentos-core.cabal
- thentos-tests/thentos-tests.cabal
thanks @np and @andorp for the idea!
> Form file upload resource handling
